# Generated by Django 5.0.2 on 2024-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phonecontact',
            field=models.CharField(max_length=40),
        ),
    ]
