# Generated by Django 5.0.2 on 2024-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_phonecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='emailcontact2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='emailcontact3',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ruc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
