# Generated by Django 5.0.2 on 2024-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_client_emailcontact3_client_emailcontact1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresscontact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='emailcontact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phonecontact',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
