# Generated by Django 5.0.2 on 2024-03-15 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_broker_agency'),
        ('client', '0006_alter_client_adresscontact_alter_client_emailcontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
    ]
