# Generated by Django 5.0.2 on 2024-03-04 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('Adquisicion', 'Adquisicion'), ('Preparacion', 'Preparacion'), ('Comercializacion', 'Comercializacion')], default='Adquisicion', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to=settings.AUTH_USER_MODEL)),
                ('prop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='property.property')),
            ],
        ),
    ]
