# Generated by Django 5.0.2 on 2024-03-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='time',
            field=models.DurationField(),
        ),
    ]
