# Generated by Django 5.0.2 on 2024-03-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_alter_process_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
