# Generated by Django 5.0.2 on 2024-03-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_process_end_date_process_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
