# Generated by Django 5.0.2 on 2024-03-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_process_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='time',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
