# Generated by Django 5.0.2 on 2024-03-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_alter_process_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='stage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='process',
            name='time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
