# Generated by Django 5.0.2 on 2024-03-06 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_alter_process_stage_alter_process_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='OnProgress',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
