# Generated by Django 5.0.2 on 2024-03-06 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_alter_process_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
