# Generated by Django 5.0.2 on 2024-03-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0015_alter_process_end_date'),
        ('property', '0009_alter_property_mainteinprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='property.property'),
        ),
        migrations.AlterField(
            model_name='process',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
