# Generated by Django 4.2.11 on 2024-10-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0016_alter_process_prop_alter_process_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
