# Generated by Django 5.0.2 on 2024-03-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_society_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='ruc',
            field=models.CharField(max_length=255),
        ),
    ]
