# Generated by Django 5.0.2 on 2024-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_alter_society_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='ruc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
