# Generated by Django 5.0.2 on 2024-03-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='agency',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
