# Generated by Django 5.0.2 on 2024-03-04 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
        ('lead', '0001_initial'),
        ('property', '0002_alter_property_currentlease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='priority',
        ),
        migrations.AlterField(
            model_name='lead',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='broker.broker'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='property_interested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_leads', to='property.property'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Prospecto', 'Prospecto')], default='Lead', max_length=10),
        ),
    ]
