# Generated by Django 5.0.2 on 2024-03-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_remove_lead_priority_alter_lead_broker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Prospecto', 'Prospecto'), ('Cliente', 'Cliente')], default='Lead', max_length=10),
        ),
    ]
