# Generated by Django 5.0.2 on 2024-03-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_remove_lead_converted_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
