# Generated by Django 5.0.2 on 2024-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_lead_state_alter_lead_email_alter_lead_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(choices=[(None, None), ('Abierto', 'Abierto'), ('Cerrado', 'Cerrado'), ('Perdido', 'Perdido')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[(None, None), ('Lead', 'Lead'), ('Prospecto', 'Prospecto'), ('Cliente', 'Cliente')], default=None, max_length=10),
        ),
    ]
