# Generated by Django 5.0.2 on 2024-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_alter_lead_state_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado'), ('Perdido', 'Perdido')], default='Abierto', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Prospecto', 'Prospecto'), ('Cliente', 'Cliente')], default='Lead', max_length=10),
        ),
    ]
