# Generated by Django 4.2.11 on 2024-10-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_alter_lead_state_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fuente',
            field=models.CharField(blank=True, choices=[('Broker', 'Broker'), ('Letrero', 'Letrero'), ('CompreoAlquile', 'CompreoAlquile'), ('CampañaInstagram', 'CampañaInstagram'), ('Otro', 'Otro')], max_length=30, null=True),
        ),
    ]
