# Generated by Django 5.0.2 on 2024-03-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_currentlease'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='increase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
