# Generated by Django 5.0.2 on 2024-03-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_admin_property_adminemail_and_more'),
        ('society', '0003_alter_society_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='society.society'),
        ),
    ]
