# Generated by Django 5.0.2 on 2024-03-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lastincrease',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='costxm2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='mainteinprice',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='maintxm2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='rentprice',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20),
        ),
    ]
