# Generated by Django 5.0.2 on 2024-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_newcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='mainteinprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='rentprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
