# Generated by Django 5.0.2 on 2024-03-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_mainteinprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='newcontract',
        ),
    ]
